/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto1.ventanas;

import java.awt.BorderLayout;
import proyecto1.elementos.compracod;
import proyecto1.elementos.cotizacioncod;
import proyecto1.elementos.regionescod;
//import java.util.ArrayList;
import proyecto1.elementos.registrocod;
import proyecto1.ventanas.paneles.Datosfactupanel;
import proyecto1.ventanas.paneles.Kioskopanel;
import proyecto1.ventanas.paneles.Municipiopanel;
import proyecto1.ventanas.paneles.Regionestab;
import proyecto1.ventanas.paneles.adminop;
import proyecto1.ventanas.paneles.comprapanel;
import proyecto1.ventanas.paneles.cuentapa;
import proyecto1.ventanas.paneles.departpanel;
import proyecto1.ventanas.paneles.enviossolittab;
import proyecto1.ventanas.paneles.login;
import proyecto1.ventanas.paneles.menu;
import proyecto1.ventanas.paneles.multiplepanel;
import proyecto1.ventanas.paneles.registro;
import proyecto1.ventanas.paneles.repor2pan;
import proyecto1.ventanas.paneles.reporte3pan;
import proyecto1.ventanas.paneles.tablaregiones;
import proyecto1.ventanas.paneles.tarjetastab;

/**
 *
 * @author Pedro
 */
public class ventana extends javax.swing.JFrame {
private login log = new login();
private menu men = new menu();
private registro reg = new registro();
private adminop admintab = new adminop();
private Regionestab regtab = new Regionestab();
private tablaregiones tabregio = new tablaregiones();
public departpanel deptotab = new departpanel();
private Municipiopanel munitabb = new Municipiopanel();
private Kioskopanel kiostab = new Kioskopanel();
private tarjetastab tarjtab = new tarjetastab();
private Datosfactupanel factupanel = new Datosfactupanel();
private multiplepanel multipan = new multiplepanel();
private comprapanel comprapanell = new comprapanel();
private enviossolittab enviospan = new enviossolittab();
private repor2pan repo2pann = new repor2pan();
private reporte3pan repo3 = new reporte3pan();
private cuentapa cuentachange = new cuentapa();
private String usuarioactivo = "";

private regionescod regionMetropolitana = new regionescod("(M)", "Metropolitana", 35.00,25.00);
private regionescod regionNorte = new regionescod("(NT)", "Norte", 68.50,45.55);
private regionescod regionNororiente = new regionescod("(NO)", "Nororiente", 58.68,35.48);
private regionescod regionSuroriente = new regionescod("(SO)", "Suroriente", 38.68,32.48);
private regionescod regionSuroccidente = new regionescod("(SOC)", "Suroccidente", 34.00,29.00);
private regionescod regionNoroccidente = new regionescod("(NOC)", "Noroccidente", 44.50,40.00);
    /**
     * Creates new form ventana
     */
    public ventana() {
        initComponents();
        cambiarPanel(log);
        Reporteb.setVisible(false);
        regkiosco.setVisible(false);
        regpre.setVisible(false);
        depbut.setVisible(false); 
        munibut.setVisible(false);
        mostrarregact.setVisible(false);
        salirbut.setVisible(false);
        cotpaqbut.setVisible(false);
        descargabut.setVisible(false);
        regdatbut.setVisible(false);
        regtarbut.setVisible(false);
        comprabut.setVisible(false);
        verenviosbut.setVisible(false);
        jPanel3.setVisible(false);
        regtab.setRegiones(regionMetropolitana, regionNorte, regionNororiente, regionSuroriente, regionSuroccidente, regionNoroccidente);
        deptotab.setRegiones(regionMetropolitana, regionNorte, regionNororiente, regionSuroriente, regionSuroccidente, regionNoroccidente);
        multipan.setRegiones2(regionMetropolitana, regionNorte, regionNororiente, regionSuroriente, regionSuroccidente, regionNoroccidente);
        
        
    }

    private void cambiarPanel(javax.swing.JPanel miPanel){
        miPanel.setSize(716, 477);
        miPanel.setLocation(0, 0);
        jPanel1.removeAll();
        jPanel1.add(miPanel, BorderLayout.CENTER);
        jPanel1.revalidate();
        jPanel1.repaint();  
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Login = new javax.swing.JButton();
        etiquetaError = new javax.swing.JLabel();
        Registrar = new javax.swing.JButton();
        regresar = new javax.swing.JButton();
        regkiosco = new javax.swing.JButton();
        regpre = new javax.swing.JButton();
        depbut = new javax.swing.JButton();
        Reporteb = new javax.swing.JButton();
        mostrarregact = new javax.swing.JButton();
        munibut = new javax.swing.JButton();
        salirbut = new javax.swing.JButton();
        cuentabutton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        regdatbut = new javax.swing.JButton();
        regtarbut = new javax.swing.JButton();
        cotpaqbut = new javax.swing.JButton();
        comprabut = new javax.swing.JButton();
        descargabut = new javax.swing.JButton();
        verenviosbut = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        Reporte1 = new javax.swing.JButton();
        Reporte2 = new javax.swing.JButton();
        Reporte3 = new javax.swing.JButton();
        Reporte4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 255, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 716, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 477, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));

        Login.setText("Login");
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });

        etiquetaError.setText("...");

        Registrar.setText("Registrar");
        Registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarActionPerformed(evt);
            }
        });

        regresar.setText("Regresar");
        regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarActionPerformed(evt);
            }
        });

        regkiosco.setText("Registrar kiosco");
        regkiosco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regkioscoActionPerformed(evt);
            }
        });

        regpre.setText("Reg. y prec.");
        regpre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regpreActionPerformed(evt);
            }
        });

        depbut.setText("Departamento");
        depbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depbutActionPerformed(evt);
            }
        });

        Reporteb.setText("Reportes");
        Reporteb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReportebActionPerformed(evt);
            }
        });

        mostrarregact.setText("Mostrar todas las regiones");
        mostrarregact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarregactActionPerformed(evt);
            }
        });

        munibut.setText("Municipio");
        munibut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                munibutActionPerformed(evt);
            }
        });

        salirbut.setText("Salir");
        salirbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirbutActionPerformed(evt);
            }
        });

        cuentabutton.setText("Cuenta");
        cuentabutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuentabuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Reporteb, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(regkiosco, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(regpre)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(munibut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(depbut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(etiquetaError)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(mostrarregact)))
                        .addGap(46, 46, 46)
                        .addComponent(salirbut))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Login)
                        .addGap(73, 73, 73)
                        .addComponent(Registrar)
                        .addGap(27, 27, 27)
                        .addComponent(cuentabutton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 302, Short.MAX_VALUE)
                        .addComponent(regresar)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Login)
                    .addComponent(Registrar)
                    .addComponent(regresar)
                    .addComponent(cuentabutton))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(etiquetaError)
                            .addComponent(mostrarregact))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(regkiosco)
                            .addComponent(regpre)
                            .addComponent(depbut))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Reporteb)
                            .addComponent(munibut)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(salirbut)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 102));

        regdatbut.setText("Registro de datos de facturacion");
        regdatbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regdatbutActionPerformed(evt);
            }
        });

        regtarbut.setText("Registro de tarjeta de credito/debito");
        regtarbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regtarbutActionPerformed(evt);
            }
        });

        cotpaqbut.setText("Cotizacion de paquetes");
        cotpaqbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cotpaqbutActionPerformed(evt);
            }
        });

        comprabut.setText("Compra");
        comprabut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprabutActionPerformed(evt);
            }
        });

        descargabut.setText("Descargar factura y guía");

        verenviosbut.setText(" Ver envíos solicitados");
        verenviosbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verenviosbutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(regtarbut)
                    .addComponent(cotpaqbut)
                    .addComponent(comprabut)
                    .addComponent(descargabut)
                    .addComponent(verenviosbut)
                    .addComponent(regdatbut))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(regdatbut)
                .addGap(18, 18, 18)
                .addComponent(regtarbut)
                .addGap(18, 18, 18)
                .addComponent(cotpaqbut)
                .addGap(18, 18, 18)
                .addComponent(comprabut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(descargabut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(verenviosbut)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(51, 255, 204));

        Reporte1.setText("Reporte1");
        Reporte1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Reporte1ActionPerformed(evt);
            }
        });

        Reporte2.setText("Reporte2");
        Reporte2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Reporte2ActionPerformed(evt);
            }
        });

        Reporte3.setText("Reporte3");
        Reporte3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Reporte3ActionPerformed(evt);
            }
        });

        Reporte4.setText("Reporte4");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(Reporte1)
                        .addGap(18, 18, 18)
                        .addComponent(Reporte2))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(Reporte3)
                        .addGap(18, 18, 18)
                        .addComponent(Reporte4)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Reporte1)
                    .addComponent(Reporte2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Reporte3)
                    .addComponent(Reporte4))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
        // TODO add your handling code here:

        for(int i =0;i<reg.getregistrocod().size();i++){
            registrocod temporal = new registrocod();
            temporal=reg.getregistrocod().get(i);               
        if(log.getUsuario().equals(temporal.getCorreo()) && log.getClave().equals(temporal.getcontra()) ){
            if (log.getUsuario().equals("ipc1_202004730@ipc1delivery.com") && log.getClave().equals("202004730")) {
                cambiarPanel(admintab);
                jPanel2.setVisible(true);
                admintab.setVisible(true);
                Reporteb.setVisible(true);
                regkiosco.setVisible(true);
                regpre.setVisible(true);
                depbut.setVisible(true);
                munibut.setVisible(true);
                salirbut.setVisible(true);
                Login.setVisible(false);
                Registrar.setVisible(false);
                regresar.setVisible(false);
                cotpaqbut.setVisible(false);
                descargabut.setVisible(false);
                regdatbut.setVisible(false);
                regtarbut.setVisible(false);
                comprabut.setVisible(false);
                verenviosbut.setVisible(false);
                jPanel3.setVisible(false);
                break;
            }else{
            usuarioactivo=log.getUsuario();
            tarjtab.setDato(log.getUsuario());
            factupanel.setDato2(log.getUsuario());
            comprapanell.setDatos0(log.getUsuario());
            enviospan.setDatosf(log.getUsuario());
            
            cambiarPanel(men);
            Login.setVisible(false);
            Registrar.setVisible(false);
            regresar.setVisible(false);
            jPanel2.setVisible(true);
            men.setVisible(true);
            cotpaqbut.setVisible(true);
            descargabut.setVisible(true);
            regdatbut.setVisible(true);
            regtarbut.setVisible(true);
            comprabut.setVisible(true);
            verenviosbut.setVisible(true);
            salirbut.setVisible(true);
            jPanel3.setVisible(true);
            multipan.setDato1(temporal.getynkiosko());
            multipan.setDatou(log.getUsuario());
//                System.out.println(usuarioactivo);
            break;}
        }else{
            etiquetaError.setText("Usuario o Clave incorrectas, intente nuevamente");
        }
        }
    }//GEN-LAST:event_LoginActionPerformed

    private void RegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarActionPerformed
        // TODO add your handling code here:
        reg.setListaKioskos(kiostab.getkioskocod());
        reg.crearListaDesplegable4();
        cambiarPanel(reg);
            jPanel2.setVisible(true);
            reg.setVisible(true);
            
    }//GEN-LAST:event_RegistrarActionPerformed

    private void regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarActionPerformed
        // TODO add your handling code here:
        cambiarPanel(log);
            jPanel2.setVisible(true);
            reg.setVisible(false);
            mostrarregact.setVisible(false);
    }//GEN-LAST:event_regresarActionPerformed

    private void regpreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regpreActionPerformed
        cambiarPanel(regtab);
            jPanel2.setVisible(true);
            mostrarregact.setVisible(true);
    }//GEN-LAST:event_regpreActionPerformed

    private void mostrarregactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarregactActionPerformed
       cambiarPanel(tabregio);
        tabregio.setVisible((true));
        jPanel2.setVisible(true);
        regionMetropolitana = regtab.getMetropolitana();
        tabregio.setMetropolitana("Codigo: " + regionMetropolitana.getCodreg()+" Nombre: " + regionMetropolitana.getnombrereg()+" Precio estandar: Q."+ regionMetropolitana.getprecioest()+" Precio especial: Q."+ regionMetropolitana.getprecioesp());
        
        regionNorte = regtab.getNorte();
        tabregio.setNorte("Codigo: " + regionNorte.getCodreg()+" Nombre: " + regionNorte.getnombrereg()+" Precio estandar: Q."+ regionNorte.getprecioest()+" Precio especial: Q."+ regionNorte.getprecioesp());
        
        regionNororiente = regtab.getNororiente();
        tabregio.setNororiente("Codigo: " + regionNororiente.getCodreg()+" Nombre: " + regionNororiente.getnombrereg()+" Precio estandar: Q."+ regionNororiente.getprecioest()+" Precio especial: Q."+ regionNororiente.getprecioesp());
        
        regionSuroriente = regtab.getSuroriente();
        tabregio.setSuroriente("Codigo: " + regionSuroriente.getCodreg()+" Nombre: " + regionSuroriente.getnombrereg()+" Precio estandar: Q."+ regionSuroriente.getprecioest()+" Precio especial: Q."+ regionSuroriente.getprecioesp());
        
        regionSuroccidente = regtab.getSuroccidente();
        tabregio.setSuroccidente("Codigo: " + regionSuroccidente.getCodreg()+" Nombre: " + regionSuroccidente.getnombrereg()+" Precio estandar: Q."+ regionSuroccidente.getprecioest()+" Precio especial: Q."+ regionSuroccidente.getprecioesp());
        
        regionNoroccidente = regtab.getNoroccidente();
        tabregio.setNoroccidente("Codigo: " + regionNoroccidente.getCodreg()+" Nombre: " + regionNoroccidente.getnombrereg()+" Precio estandar: Q."+ regionNoroccidente.getprecioest()+" Precio especial: Q."+ regionNoroccidente.getprecioesp());
        
 
        
    }//GEN-LAST:event_mostrarregactActionPerformed

    private void depbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depbutActionPerformed
        // TODO add your handling code here:
        cambiarPanel(deptotab);
            jPanel2.setVisible(true);
    }//GEN-LAST:event_depbutActionPerformed

    private void munibutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_munibutActionPerformed
        // TODO add your handling code here:
        munitabb.setListaDeptos(deptotab.getdeptoscod());
        munitabb.crearListaDesplegable();
        cambiarPanel(munitabb);
        jPanel2.setVisible(true);
    }//GEN-LAST:event_munibutActionPerformed

    private void regkioscoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regkioscoActionPerformed
     
        kiostab.setListaDeptos2(deptotab.getdeptoscod());
//        kiostab.crearListaDesplegable2();  
        kiostab.setListaDeptos3(munitabb.getMunicipiocod());
//        kiostab.crearListaDesplegable3(); 
        cambiarPanel(kiostab);
        jPanel2.setVisible(true);
        
    }//GEN-LAST:event_regkioscoActionPerformed

    private void salirbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirbutActionPerformed
       cambiarPanel(log);
            jPanel2.setVisible(true);
            Reporteb.setVisible(false);
            depbut.setVisible(false);
            mostrarregact.setVisible(false);
            munibut.setVisible(false);
            regkiosco.setVisible(false);
            regpre.setVisible(false);
            regresar.setVisible(true);
            salirbut.setVisible(false);
            Login.setVisible(true);
            Registrar.setVisible(true);
                cotpaqbut.setVisible(false);
            descargabut.setVisible(false);
            regdatbut.setVisible(false);
            regtarbut.setVisible(false);
            comprabut.setVisible(false);
            verenviosbut.setVisible(false);
            salirbut.setVisible(false);
            jPanel3.setVisible(false);
    }//GEN-LAST:event_salirbutActionPerformed

    private void regtarbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regtarbutActionPerformed
       cambiarPanel(tarjtab);
            jPanel2.setVisible(true);
    }//GEN-LAST:event_regtarbutActionPerformed

    private void regdatbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regdatbutActionPerformed
        cambiarPanel(factupanel);
            jPanel2.setVisible(true);
    }//GEN-LAST:event_regdatbutActionPerformed

    private void cotpaqbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cotpaqbutActionPerformed
        multipan.setListaDeptosss(deptotab.getdeptoscod());
        multipan.setListamuniss(munitabb.getMunicipiocod());
        cambiarPanel(multipan);
            jPanel2.setVisible(true);
            
    }//GEN-LAST:event_cotpaqbutActionPerformed

    private void comprabutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprabutActionPerformed
            comprapanell.setListacoti(multipan.getcotizacioncod());
            comprapanell.crearListaDesplegablec1();
            comprapanell.setListatarj(tarjtab.gettarjetacod());
            comprapanell.crearListaDesplegablec2();
            comprapanell.setListafactu(factupanel.getfacturacioncod());
            comprapanell.crearListaDesplegablec3();
            cambiarPanel(comprapanell);
            jPanel3.setVisible(true);
            jPanel2.setVisible(true);
    }//GEN-LAST:event_comprabutActionPerformed

    private void verenviosbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verenviosbutActionPerformed
        String textoenvios="<html><head></head><body><table><tr><th>Codigo</th><th>Tipo de servicio</th><th>Destinatario</th><th>Total de envio</th><th>Tipo de pago</th></tr>";        
        for(int rt=0; rt<comprapanell.getcompracod().size();rt++){
            compracod temporalr = new compracod();
            temporalr = comprapanell.getcompracod().get(rt);
            for (int yu = 0; yu <multipan.getcotizacioncod().size() ; yu++) {
               cotizacioncod temporayu = new cotizacioncod();
            temporayu = multipan.getcotizacioncod().get(yu);  
                if (usuarioactivo.equals(temporayu.getNombreusuario())) {
                    
                
                if (temporayu.getCodigo()==temporalr.getPaqcod()) {
                    textoenvios = textoenvios+"<tr><td>"+temporalr.getPaqcod()+"</td><td>"+temporayu.getTipservicio()+"</td><td>"+temporayu.getDepdestino()+temporayu.getMunidestino()+"</td><td>"+temporalr.getTotalQQ()+"</td><td>"+temporalr.getTipodepago()  +"</td></tr>" ;         
                }
                }
            }           
        }
        
        textoenvios=textoenvios+"</table></body></html>";
        enviospan.setTextArea(textoenvios);
        cambiarPanel(enviospan);
         jPanel2.setVisible(true);        
    }//GEN-LAST:event_verenviosbutActionPerformed

    private void ReportebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReportebActionPerformed
       Reporte1.setVisible(true);
       Reporte2.setVisible(true);
       Reporte3.setVisible(true);
       Reporte4.setVisible(true);
       
    }//GEN-LAST:event_ReportebActionPerformed

    private void Reporte2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Reporte2ActionPerformed
        repo2pann.setListcoot(multipan.getcotizacioncod());
        repo2pann.setListcoomp(comprapanell.getcompracod());
        cambiarPanel(repo2pann);
         jPanel2.setVisible(true);  
         jPanel4.setVisible(true);
    }//GEN-LAST:event_Reporte2ActionPerformed

    private void Reporte3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Reporte3ActionPerformed
         repo3.setListcopra3(comprapanell.getcompracod());
        cambiarPanel(repo3);
         jPanel2.setVisible(true);  
         jPanel4.setVisible(true);
    }//GEN-LAST:event_Reporte3ActionPerformed

    private void Reporte1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Reporte1ActionPerformed
       
    }//GEN-LAST:event_Reporte1ActionPerformed

    private void cuentabuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuentabuttonActionPerformed
       cuentachange.setcor(usuarioactivo);
       cuentachange.setListadat(reg.getregistrocod());
        cambiarPanel(cuentachange);
         jPanel2.setVisible(true);        
        
        
    }//GEN-LAST:event_cuentabuttonActionPerformed

    public void recocoti(){
        for(int rt=0; rt<comprapanell.getcompracod().size();rt++){
            compracod temporalr = new compracod();
            temporalr = comprapanell.getcompracod().get(rt); 
            }
    }
    
    public void recuentoM(){
        for(int rt=0; rt<comprapanell.getcompracod().size();rt++){
            compracod temporalr = new compracod();
            temporalr = comprapanell.getcompracod().get(rt); 
            }
    }

//static ArrayList <registrocod> listadatos = new ArrayList <registrocod>();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Login;
    private javax.swing.JButton Registrar;
    private javax.swing.JButton Reporte1;
    private javax.swing.JButton Reporte2;
    private javax.swing.JButton Reporte3;
    private javax.swing.JButton Reporte4;
    private javax.swing.JButton Reporteb;
    private javax.swing.JButton comprabut;
    private javax.swing.JButton cotpaqbut;
    private javax.swing.JButton cuentabutton;
    private javax.swing.JButton depbut;
    private javax.swing.JButton descargabut;
    private javax.swing.JLabel etiquetaError;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton mostrarregact;
    private javax.swing.JButton munibut;
    private javax.swing.JButton regdatbut;
    private javax.swing.JButton regkiosco;
    private javax.swing.JButton regpre;
    private javax.swing.JButton regresar;
    private javax.swing.JButton regtarbut;
    private javax.swing.JButton salirbut;
    private javax.swing.JButton verenviosbut;
    // End of variables declaration//GEN-END:variables
}
