/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package proyecto1.ventanas.paneles;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import proyecto1.elementos.Municipiocod;
import proyecto1.elementos.cotizacioncod;
import proyecto1.elementos.departamentoscod;
import proyecto1.elementos.kioskocod;
import proyecto1.elementos.regionescod;

/**
 *
 * @author Pedro
 */
public class multiplepanel extends javax.swing.JPanel {
private String datoo;
private Kioskopanel kiostab = new Kioskopanel();
//private departpanel deptotab = new departpanel();
private Regionestab regtab = new Regionestab();
private regionescod regionMetropolitana = new regionescod();
//private Municipiopanel munitabb = new Municipiopanel();
private regionescod regionNorte = new regionescod();
private regionescod regionNororiente = new regionescod();
private regionescod regionSuroriente = new regionescod();
private regionescod regionSuroccidente = new regionescod();
private regionescod regionNoroccidente = new regionescod();
regionescod Metropolitana = new regionescod();
regionescod Norte = new regionescod();
regionescod Nororiente = new regionescod();
regionescod Suroriente = new regionescod();
regionescod Suroccidente = new regionescod();
regionescod Noroccidente = new regionescod();
private String vtampaq="";
private String vtipserv="";
private double precioestandarv=0.00;
private double precioespecialv=0.00;
private double tamv=0;
private double totalQ=0.00;
private String datou;
private int contadorr=0;
private String coodd="";
private String coodd1="";

    /**
     * Creates new form multiplepanel
     */
    public multiplepanel() {
        initComponents();
    regtab.setRegiones(regionMetropolitana, regionNorte, regionNororiente, regionSuroriente, regionSuroccidente, regionNoroccidente);
    }
    
    public void setDato1(String datoo){// para obtener el valor de rol segun el array de registro
        this.datoo=datoo;
       
    }
    
        public void setDatou(String datou){// para obtener el valor de rol segun el array de registro
        this.datou=datou;
       
    }
    
        public void setRegiones2(regionescod Metropolitana, regionescod Norte, regionescod Nororiente, regionescod Suroriente, regionescod Suroccidente, regionescod Noroccidente){
       this.Metropolitana=Metropolitana;
        this.Norte = Norte; 
        this.Nororiente = Nororiente;
        this.Suroriente = Suroriente;
        this.Suroccidente = Suroccidente;
        this.Noroccidente = Noroccidente;
        
    }
        
    public regionescod getMetropolitana(){
        return Metropolitana;
    }
     public regionescod getNorte(){
        return Norte;
    }
     public regionescod getNororiente(){
        return Nororiente;
    }
     public regionescod getSuroriente(){
        return Suroriente;
    }
     public regionescod getSuroccidente(){
        return Suroccidente;
    }
     public regionescod getNoroccidente(){
        return Noroccidente;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo1 = new javax.swing.ButtonGroup();
        grupo2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        deporigentext = new javax.swing.JComboBox<>();
        muniorigentext = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        depdestinotext = new javax.swing.JComboBox<>();
        munidesttext = new javax.swing.JComboBox<>();
        npaquetestext = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        cargardatosbut = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Cotizarbuton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        total1label = new javax.swing.JLabel();
        total2label = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        direccion1text = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        direccion2text = new javax.swing.JTextField();
        pequenocanti = new javax.swing.JTextField();
        mediantamano = new javax.swing.JTextField();
        grandetamano = new javax.swing.JTextField();
        preciosbut = new javax.swing.JButton();
        muni2 = new javax.swing.JButton();
        muni22 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 153, 153));

        jLabel1.setText("Origen");

        deporigentext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deporigentextActionPerformed(evt);
            }
        });

        muniorigentext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                muniorigentextActionPerformed(evt);
            }
        });

        jLabel2.setText("Destino");

        munidesttext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                munidesttextActionPerformed(evt);
            }
        });

        jLabel3.setText("Numero de paquetes");

        jLabel4.setText("Tamano de paquetes");

        grupo1.add(jRadioButton1);
        jRadioButton1.setText("Pequeno");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        grupo1.add(jRadioButton2);
        jRadioButton2.setText("Mediano");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        grupo1.add(jRadioButton3);
        jRadioButton3.setText("Grande");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        cargardatosbut.setText("Cargar  datos");
        cargardatosbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargardatosbutActionPerformed(evt);
            }
        });

        jLabel5.setText("Departamento");

        jLabel6.setText("Municipio");

        jLabel7.setText("Departamento");

        jLabel8.setText("Municipio");

        jLabel9.setText("<1 libra a 10 libras>");

        jLabel10.setText("<11 libras a 50 >");

        jLabel11.setText("<51 libras en adelante>");

        Cotizarbuton.setText("Cotizar");
        Cotizarbuton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CotizarbutonActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 0, 204));

        grupo2.add(jRadioButton4);
        jRadioButton4.setText("Servicio estandar");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        grupo2.add(jRadioButton5);
        jRadioButton5.setText("Servicio especial");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });

        total1label.setText(".");

        total2label.setText(".");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton4)
                    .addComponent(total1label))
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(total2label)
                    .addComponent(jRadioButton5))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton4)
                    .addComponent(jRadioButton5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(total1label)
                    .addComponent(total2label))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jLabel12.setText("Direccion");

        jLabel13.setText("Direccion");

        preciosbut.setText("Mostrar precios");
        preciosbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preciosbutActionPerformed(evt);
            }
        });

        muni2.setText("Cargas municipios");
        muni2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                muni2ActionPerformed(evt);
            }
        });

        muni22.setText("Municipio");
        muni22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                muni22ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(jLabel6))
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cargardatosbut)
                                    .addComponent(muni22, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(deporigentext, 0, 122, Short.MAX_VALUE)
                            .addComponent(muniorigentext, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel1)))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(direccion2text, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(munidesttext, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(muni2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(depdestinotext, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Cotizarbuton))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(jLabel12)
                                        .addGap(34, 34, 34)
                                        .addComponent(direccion1text, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(npaquetestext, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(preciosbut))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(180, 180, 180)
                                        .addComponent(jLabel4))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(pequenocanti, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel10)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(6, 6, 6)
                                                        .addComponent(mediantamano, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(6, 6, 6)
                                                        .addComponent(grandetamano))
                                                    .addComponent(jLabel11)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jRadioButton1)
                                                .addGap(43, 43, 43)
                                                .addComponent(jRadioButton2)
                                                .addGap(40, 40, 40)
                                                .addComponent(jRadioButton3)))))))))
                .addContainerGap(172, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(depdestinotext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cargardatosbut)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(deporigentext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(muniorigentext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(munidesttext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(muni2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(muni22)
                            .addComponent(jLabel13)
                            .addComponent(direccion2text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel12)
                                .addComponent(direccion1text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(npaquetestext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(preciosbut))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jRadioButton1)
                                .addComponent(jRadioButton2))
                            .addComponent(jRadioButton3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(mediantamano, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                            .addComponent(pequenocanti, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(grandetamano))))
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Cotizarbuton)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(115, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void munidesttextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_munidesttextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_munidesttextActionPerformed

    public void obtenercod(){
    for (int ai = 0; ai < listadeptos.size(); ai++) {
    departamentoscod temporaai = new departamentoscod();
    temporaai=listadeptos.get(ai);
        if (temporaai.getNdepto().equals(depdestinotext.getSelectedItem())) {
            coodd=temporaai.getCoddept();
        }
    }
    }
    
    public void obtenercod1(){
    for (int oi = 0; oi < listadeptos.size(); oi++) {
    departamentoscod temporaoi = new departamentoscod();
    temporaoi=listadeptos.get(oi);
        if (temporaoi.getNdepto().equals(deporigentext.getSelectedItem())) {
            coodd1=temporaoi.getCoddept();
        }
    }
    }
    public void mostrardepmun(){
    for (int s = 0; s < listadeptos.size(); s++) {
    departamentoscod temporal2 = new departamentoscod();
    temporal2=listadeptos.get(s);
    deporigentext.addItem(temporal2.getNdepto());
    depdestinotext.addItem(temporal2.getNdepto());
    }


    for (int t = 0; t < listamunicipios.size(); t++) {
    Municipiocod temporal01 = new Municipiocod();
    temporal01=listamunicipios.get(t);
    muniorigentext.addItem(temporal01.getNmunicipio());
    munidesttext.addItem(temporal01.getNmunicipio()); 
    }
    }
    private void cargardatosbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargardatosbutActionPerformed
System.out.println(datoo);  
if (!datoo.equals("NA")) {
for (int i = 0; i < kiostab.getkioskocod().size(); i++) {
    kioskocod temporal = new kioskocod();
    temporal=kiostab.getkioskocod().get(i);
    if (datoo.equals(temporal.getNkiosko())) {
        deporigentext.addItem(temporal.getDeptokiosko());
        muniorigentext.addItem(temporal.getMunikiosko());

    for (int b = 0; b < listadeptos.size(); b++) {
    departamentoscod temporalb = new departamentoscod();
    temporalb=listadeptos.get(b);
    depdestinotext.addItem(temporalb.getNdepto());
    
    }
    
//        for (int r = 0; r < listamunicipios.size(); r++) {
//    Municipiocod temporalr = new Municipiocod();
//    temporalr=listamunicipios.get(r);
//    munidesttext.addItem(temporalr.getNmunicipio());
//    }

    deporigentext.setEnabled(false);
    muniorigentext.setEnabled(false);
    System.out.println(temporal.getDeptokiosko());
}
            }    
        }else{
//            mostrardepmun();
                for (int s = 0; s < listadeptos.size(); s++) {
                departamentoscod temporal2 = new departamentoscod();
                temporal2=listadeptos.get(s);
                deporigentext.addItem(temporal2.getNdepto());

                depdestinotext.addItem(temporal2.getNdepto());
              
                }
            

//                for (int t = 0; t < listamunicipios.size(); t++) {
//                Municipiocod temporal01 = new Municipiocod();
//                temporal01=listamunicipios.get(t);
//                muniorigentext.addItem(temporal01.getNmunicipio());
//                munidesttext.addItem(temporal01.getNmunicipio());               
//            }
                deporigentext.setEnabled(true);
                muniorigentext.setEnabled(true);
        }
    }//GEN-LAST:event_cargardatosbutActionPerformed

    private void deporigentextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deporigentextActionPerformed
//        if (!datoo.equals("NA")) {
//            for (int i = 0; i < listakioskos.size(); i++) {
//                kioskocod temporal = new kioskocod();
//                temporal=kiostab.getkioskocod().get(i);
//                if (datoo.equals(temporal.getNkiosko())) {
//                    deporigentext.addItem(temporal.getDeptokiosko());
//                }
//            }
//            
//        }

       
    }//GEN-LAST:event_deporigentextActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
pequenocanti.setVisible(true);
mediantamano.setVisible(false);
mediantamano.setText("");
grandetamano.setVisible(false);
grandetamano.setText("");
vtampaq="Pequeno";


    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
pequenocanti.setVisible(false);
pequenocanti.setText("");
mediantamano.setVisible(true);
grandetamano.setVisible(false);
grandetamano.setText("");
vtampaq="Mediano";

    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
pequenocanti.setVisible(false);
pequenocanti.setText("");
mediantamano.setVisible(false);
mediantamano.setText("");
grandetamano.setVisible(true);
vtampaq="Grande";

    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void CotizarbutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CotizarbutonActionPerformed
if(direccion1text.getText().isEmpty() || direccion2text.getText().isEmpty()|| npaquetestext.getText().isEmpty() || (pequenocanti.getText().isEmpty() && mediantamano.getText().isEmpty() && grandetamano.getText().isEmpty() ) || (!jRadioButton4.isEnabled() && !jRadioButton5.isEnabled()) ){
 JOptionPane.showMessageDialog(null, "Porfavor, complete los campos","Error", JOptionPane.WARNING_MESSAGE);
}else{
    if (vtampaq.equals("Pequeno")) {
        tamv=Double.parseDouble(pequenocanti.getText());
    }else if(vtampaq.equals("Mediano")){
        tamv=Double.parseDouble(mediantamano.getText());
    }else if(vtampaq.equals("Grande")){
        tamv=Double.parseDouble(grandetamano.getText());
    }
    totalQ= (precioestandarv+precioespecialv)*tamv*Double.parseDouble(npaquetestext.getText());
    
    
    listacotizacion.add(new cotizacioncod(datou,(String) deporigentext.getSelectedItem(),(String) muniorigentext.getSelectedItem(),(String) depdestinotext.getSelectedItem(), (String) munidesttext.getSelectedItem(), direccion1text.getText(), direccion2text.getText(), Double.parseDouble(npaquetestext.getText()), vtampaq, tamv, vtipserv, precioestandarv+precioespecialv, totalQ, contadorr ));
            JOptionPane.showMessageDialog(null, "Dato anadido exitosamente","Confirmacion", JOptionPane.INFORMATION_MESSAGE);
            for(int p =0;p<listacotizacion.size();p++){
            cotizacioncod tempora6 = new cotizacioncod();
            tempora6=listacotizacion.get(p);
            System.out.println(tempora6.getNombreusuario()+" "+tempora6.getDeporigen()+" "+tempora6.getMuniorigen()+" "+tempora6.getDepdestino() +" "+tempora6.getMunidestino() +" "+tempora6.getDir1() +" "+tempora6.getDir2() +" "+tempora6.getNumpaquetes()+" "+tempora6.getTamanpaquetes()+" "+tempora6.getTampaq()+" "+tempora6.getTipservicio()+" "+tempora6.getTipserv()+" "+tempora6.getTotalcot()+" "+tempora6.getCodigo() );
        }
contadorr=contadorr+1;
totalQ=0.00;
precioespecialv=0.00;
precioestandarv=0.00;
}      
    }//GEN-LAST:event_CotizarbutonActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
vtipserv="Servicio estandar";
precioestandarv=Double.parseDouble(total1label.getText());
precioespecialv=0.00;
        
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void preciosbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preciosbutActionPerformed
        // TODO add your handling code here:
            regionMetropolitana = regtab.getMetropolitana();
            regionNorte = regtab.getNorte();
            regionNororiente = regtab.getNororiente();
            regionSuroriente = regtab.getSuroriente();
            regionSuroccidente = regtab.getSuroccidente();
            regionNoroccidente = regtab.getNoroccidente();
        for (int i = 0; i < listadeptos.size(); i++) {
                departamentoscod temporal4 = new departamentoscod();
                temporal4=listadeptos.get(i);
                
        if (deporigentext.getSelectedItem().equals(temporal4.getNdepto())) {
            System.out.println("Codigo: " + temporal4.getCodreg());   

            if (Metropolitana.getCodreg().equals(temporal4.getCodreg())) {
                total1label.setText(Metropolitana.getprecioest()+ "");
                total2label.setText(Metropolitana.getprecioesp()+ "");
                System.out.println(Metropolitana.getprecioest());
            }else if (Norte.getCodreg().equals(temporal4.getCodreg())) {
                total1label.setText(Norte.getprecioest()+ "");
                total2label.setText(Norte.getprecioesp()+ "");
                System.out.println(Norte.getprecioest());
            }else if (Nororiente.getCodreg().equals(temporal4.getCodreg())) {
                total1label.setText(Nororiente.getprecioest()+ "");
                total2label.setText(Nororiente.getprecioesp()+ "");
                System.out.println(Nororiente.getprecioest());              
            }else if (Suroriente.getCodreg().equals(temporal4.getCodreg())) {
                total1label.setText(Suroriente.getprecioest()+ "");
                total2label.setText(Suroriente.getprecioesp()+ "");
                System.out.println(Suroriente.getprecioest());
            }else if (Suroccidente.getCodreg().equals(temporal4.getCodreg())) {
                total1label.setText(Suroccidente.getprecioest()+ "");
                total2label.setText(Suroccidente.getprecioesp()+ "");
                System.out.println(Suroccidente.getprecioest());
            }else if (Noroccidente.getCodreg().equals(temporal4.getCodreg())) {
                total1label.setText(Noroccidente.getprecioest()+ "");
                total2label.setText(Noroccidente.getprecioesp()+ "");
                System.out.println(Noroccidente.getprecioest());
                
            }            
        }
        }
    }//GEN-LAST:event_preciosbutActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        vtipserv="Servicio especial";
        precioestandarv=0.00;
        precioespecialv=Double.parseDouble(total2label.getText());
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void muniorigentextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_muniorigentextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_muniorigentextActionPerformed

    private void muni2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_muni2ActionPerformed
        munidesttext.removeAllItems();
        for(int h=0; h<listamunicipios.size();h++){
            Municipiocod temporalh = new Municipiocod();
            temporalh = listamunicipios.get(h);
            obtenercod();
            if (temporalh.getCodDeptt().equals(coodd)) {
                munidesttext.addItem(temporalh.getNmunicipio());
            }
                        
        }         
        
        
    }//GEN-LAST:event_muni2ActionPerformed

    private void muni22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_muni22ActionPerformed
              muniorigentext.removeAllItems();
        for(int l=0; l<listamunicipios.size();l++){
            Municipiocod temporall = new Municipiocod();
            temporall = listamunicipios.get(l);
            obtenercod1();
            if (temporall.getCodDeptt().equals(coodd1)) {
                muniorigentext.addItem(temporall.getNmunicipio());
            }
                        
        } 
    }//GEN-LAST:event_muni22ActionPerformed
static ArrayList <kioskocod> listakioskos = new ArrayList <kioskocod>();
static ArrayList <cotizacioncod> listacotizacion = new ArrayList <cotizacioncod>();
static ArrayList <departamentoscod> listadeptos = new ArrayList <departamentoscod>();
static ArrayList <regionescod> listaregiones = new ArrayList <regionescod>();
static ArrayList <Municipiocod> listamunicipios = new ArrayList <Municipiocod>();

 public void setListaDeptosss(ArrayList <departamentoscod> listadeptos){
        this.listadeptos=listadeptos;
    }
  public void setListamuniss(ArrayList <Municipiocod> listamunicipios){
        this.listamunicipios=listamunicipios;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cotizarbuton;
    private javax.swing.JButton cargardatosbut;
    private javax.swing.JComboBox<String> depdestinotext;
    private javax.swing.JComboBox<String> deporigentext;
    private javax.swing.JTextField direccion1text;
    private javax.swing.JTextField direccion2text;
    private javax.swing.JTextField grandetamano;
    private javax.swing.ButtonGroup grupo1;
    private javax.swing.ButtonGroup grupo2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JTextField mediantamano;
    private javax.swing.JButton muni2;
    private javax.swing.JButton muni22;
    private javax.swing.JComboBox<String> munidesttext;
    private javax.swing.JComboBox<String> muniorigentext;
    private javax.swing.JTextField npaquetestext;
    private javax.swing.JTextField pequenocanti;
    private javax.swing.JButton preciosbut;
    private javax.swing.JLabel total1label;
    private javax.swing.JLabel total2label;
    // End of variables declaration//GEN-END:variables
public ArrayList<cotizacioncod> getcotizacioncod() {
        return listacotizacion;
    }
}
