/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package proyecto1.ventanas.paneles;

import java.util.ArrayList;
import proyecto1.elementos.regionescod;

/**
 *
 * @author Pedro
 */
public class Regionestab extends javax.swing.JPanel {

    /**
     * Creates new form Regionestab
     */
    regionescod Metropolitana = new regionescod();
    regionescod Norte = new regionescod();
    regionescod Nororiente = new regionescod();
    regionescod Suroriente = new regionescod();
    regionescod Suroccidente = new regionescod();
    regionescod Noroccidente = new regionescod();
    
    
    
    public Regionestab() {
        initComponents();
//            listaregiones.add(new regionescod("(M)", "Metropolitana", 35.00,25.00));
//            listaregiones.add(new regionescod("(NT)", "Norte", 68.50,45.55));
//            listaregiones.add(new regionescod("(NO)", "Nororiente", 58.68,35.48));
//            listaregiones.add(new regionescod("(SO)", "Suroriente", 38.68,32.48));
//            listaregiones.add(new regionescod("(SOC)", "Suroccidente", 34.00,25.00));
//            listaregiones.add(new regionescod("(NOC)", "Noroccidente", 44.50,40.00));
    }
    
    public void setRegiones(regionescod Metropolitana, regionescod Norte, regionescod Nororiente, regionescod Suroriente, regionescod Suroccidente, regionescod Noroccidente){
       this.Metropolitana=Metropolitana;
        this.Norte = Norte; 
        this.Nororiente = Nororiente;
        this.Suroriente = Suroriente;
        this.Suroccidente = Suroccidente;
        this.Noroccidente = Noroccidente;
        
    }
    
    public regionescod getMetropolitana(){
        return Metropolitana;
    }
     public regionescod getNorte(){
        return Norte;
    }
     public regionescod getNororiente(){
        return Nororiente;
    }
     public regionescod getSuroriente(){
        return Suroriente;
    }
     public regionescod getSuroccidente(){
        return Suroccidente;
    }
     public regionescod getNoroccidente(){
        return Noroccidente;
    }
     
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        comboreg = new javax.swing.JComboBox<>();
        codregi = new javax.swing.JTextField();
        precesta = new javax.swing.JTextField();
        precesp = new javax.swing.JTextField();
        mostardat = new javax.swing.JButton();
        actualizarreg = new javax.swing.JButton();

        jLabel1.setText("Region");

        jLabel2.setText("Codigo");

        jLabel3.setText("Precio estandar");

        jLabel4.setText("Precio especial");

        comboreg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Metropolitana", "Norte", "Nororiente", "Suroriente", "Suroccidente", "Noroccidente" }));

        mostardat.setText("Mostrar datos");
        mostardat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostardatActionPerformed(evt);
            }
        });

        actualizarreg.setText("Actualizar");
        actualizarreg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarregActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mostardat)
                        .addGap(46, 46, 46)
                        .addComponent(actualizarreg, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)))
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(comboreg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(codregi, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(precesta)
                            .addComponent(precesp))))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comboreg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(codregi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(precesta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(precesp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mostardat)
                    .addComponent(actualizarreg))
                .addContainerGap(43, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void mostardatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostardatActionPerformed
        // TODO add your handling code here:
        String opcion = comboreg.getSelectedItem().toString();
        switch(opcion){
            case  "Metropolitana":{
            codregi.setText(Metropolitana.getCodreg());
            precesta.setText(Metropolitana.getprecioest()+"");
            precesp.setText(Metropolitana.getprecioesp()+"");
            break;}
           case  "Norte":{
              codregi.setText(Norte.getCodreg());
            precesta.setText(Norte.getprecioest()+"");
            precesp.setText(Norte.getprecioesp()+"");  
           break;}
            case "Nororiente":{
                codregi.setText(Nororiente.getCodreg());
            precesta.setText(Nororiente.getprecioest()+"");
            precesp.setText(Nororiente.getprecioesp()+"");
            break;}
            case "Suroriente":{
                codregi.setText(Suroriente.getCodreg());
            precesta.setText(Suroriente.getprecioest()+"");
            precesp.setText(Suroriente.getprecioesp()+"");
            break;}
            case "Suroccidente":{
                codregi.setText(Suroccidente.getCodreg());
            precesta.setText(Suroccidente.getprecioest()+"");
            precesp.setText(Suroccidente.getprecioesp()+"");
            break;}
            case "Noroccidente": {   
              codregi.setText(Noroccidente.getCodreg());
            precesta.setText(Noroccidente.getprecioest()+"");
            precesp.setText(Noroccidente.getprecioesp()+"");
            break;}           
            
        }
    }//GEN-LAST:event_mostardatActionPerformed

    private void actualizarregActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarregActionPerformed
        
       String opcion = comboreg.getSelectedItem().toString();
        switch(opcion){
            case  "Metropolitana":{           
            Metropolitana.setprecioest(Double.parseDouble(precesta.getText()));
            Metropolitana.setprecioesp(Double.parseDouble(precesp.getText()));
            break;}
           case  "Norte":{
            Norte.setprecioest(Double.parseDouble(precesta.getText()));
            Norte.setprecioesp(Double.parseDouble(precesp.getText()));  
           break;}
            case "Nororiente":{
            Nororiente.setprecioest(Double.parseDouble(precesta.getText()));
            Nororiente.setprecioesp(Double.parseDouble(precesp.getText()));
            break;}
            case "Suroriente":{
            Suroriente.setprecioest(Double.parseDouble(precesta.getText()));
            Suroriente.setprecioesp(Double.parseDouble(precesp.getText()));
            break;}
            case "Suroccidente":{
            Suroccidente.setprecioest(Double.parseDouble(precesta.getText()));
            Suroccidente.setprecioesp(Double.parseDouble(precesp.getText()));
            break;}
            case "Noroccidente": {   
            Noroccidente.setprecioest(Double.parseDouble(precesta.getText()));
            Noroccidente.setprecioesp(Double.parseDouble(precesp.getText()));
            break;}           
            
        }
    }//GEN-LAST:event_actualizarregActionPerformed
 static ArrayList <regionescod> listaregiones = new ArrayList <regionescod>();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizarreg;
    private javax.swing.JTextField codregi;
    private javax.swing.JComboBox<String> comboreg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton mostardat;
    private javax.swing.JTextField precesp;
    private javax.swing.JTextField precesta;
    // End of variables declaration//GEN-END:variables
public ArrayList<regionescod> getregionescod() {
        return listaregiones;
    }
}
