/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package proyecto1.ventanas.paneles;

/**
 *
 * @author Pedro
 */
public class tablaregiones extends javax.swing.JPanel {

    /**
     * Creates new form tablaregiones
     */
    public tablaregiones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();
        label4 = new javax.swing.JLabel();
        label5 = new javax.swing.JLabel();
        label6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 51));

        jLabel1.setText("Informacion de regiones");

        label1.setText("...");

        label2.setText("...");

        label3.setText("...");

        label4.setText("...");

        label5.setText("...");

        label6.setText("...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label6)
                    .addComponent(label5)
                    .addComponent(label4)
                    .addComponent(label3)
                    .addComponent(label2)
                    .addComponent(label1)
                    .addComponent(jLabel1))
                .addContainerGap(222, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(label1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label2)
                .addGap(18, 18, 18)
                .addComponent(label3)
                .addGap(18, 18, 18)
                .addComponent(label4)
                .addGap(18, 18, 18)
                .addComponent(label5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label6)
                .addContainerGap(50, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

public void setMetropolitana(String informacion){
    label1.setText(informacion);
}
public void setNorte(String informacion1){
    label2.setText(informacion1);
}
public void setNororiente(String informacion2){
    label3.setText(informacion2);
}
public void setSuroriente(String informacion3){
    label4.setText(informacion3);
}
public void setSuroccidente(String informacion4){
    label5.setText(informacion4);
}
public void setNoroccidente(String informacion5){
    label6.setText(informacion5);
}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label4;
    private javax.swing.JLabel label5;
    private javax.swing.JLabel label6;
    // End of variables declaration//GEN-END:variables
}
